{{- if .Values.secret.configtx -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-configtx.yaml
data:
  configtx.yaml: |- 
    {{ $.Files.Get "configtx.yaml" | b64enc }}
{{- end }} {{- /* if secret.configtx */ -}}
