{{- if .Values.secret.genesis -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-genesis.block
data:
  genesis.block: |-
      {{ $.Files.Get "channel-artifacts/genesis.block" | b64enc }}
{{- end }} {{- /* if secret.genesis */ -}}
